In [20]:
import pandas as pd
import numpy as np
url = 'pedidos_narashop.csv'
df = pd.read_csv(url, encoding='latin-1', sep=';')
df = pd.read_csv(url, encoding='utf8', sep=';')
df.head()

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3

In [ ]:
f = pd.DataFrame({'x': [1,2,3]})
display(f)

In [13]:

print(display(df))

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12
1,10002,Leandro Reis,EletrÃ´nicos,SSD Externo,Entregue,4,599.89,8
2,10003,FlÃ¡via Azevedo,EletrÃ´nicos,Notebook,Entregue,5,3774.96,5
3,10004,Lucas Ribeiro,Esportes,Garrafa TÃ©rmica,Entregue,1,87.67,4
4,10005,VinÃ­cius Lopes,EletrÃ´nicos,SSD Externo,Entregue,3,439.02,3
...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5
19996,29997,Ana Lima,Casa e DecoraÃ§Ã£o,Tapete Sala,Em trÃ¢nsito,4,166.27,5
19997,29998,PatrÃ­cia Rocha,EletrÃ´nicos,Tablet,Cancelado,5,1577.65,4
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9
19999,30000,Thiago Santos,Casa e DecoraÃ§Ã£o,Quadro Decorativo,Em trÃ¢nsito,3,65.70,18

None

In [16]:
array_var = np.array(df['prazo_entrega_dias'])
array_quant = np.array(df['quantidade'])
array_valor_unitario = np.array(df['valor_unitario'])
print(array_quant)
print(array_valor_unitario)

media = np.mean(array_var)
mediana = np.median(array_var)
dist = (media - mediana) / mediana
print(f"Média: {media:.2f}")
print(f"Mediana: {mediana:.2f}")
print(f"Distância: {dist:.2%}")
print(f"quantidade: {dist:.2%}")

[5 4 5 ... 5 4 3]
[  98.01  599.89 3774.96 ... 1577.65  144.59   65.7 ]
Média: 8.29
Mediana: 8.00
Distância: 3.61%
quantidade: 3.61%

In [7]:
array_var = np.array(df['valor_unitario'])
media = np.mean(array_var)
mediana = np.median(array_var)
dist = (media - mediana) / mediana

print(f"Média: {media:.2f}")
print(f"Mediana: {mediana:.2f}")
print(f"Distância: {dist:.2%}")

Média: 842.82
Mediana: 295.46
Distância: 185.26%